# handler-script-loader configuration
# 
# The LIX4J language reference:
# https://github.com/inc0g-repoz/lix4j
# 
# Make sure you are using valid event types. Use the link below for reference:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/package-summary.html

# Function mapping
scripts:
  example:
    enabled: true
    file: "scripts/example.script"
    
    # Mappings for event handlers
    events:
      on-player-death:
        event-class: "org.bukkit.event.entity.PlayerDeathEvent"
        function: "onPlayerDeath"
        priority: "NORMAL"
      on-block-break:
        event-class: "org.bukkit.event.block.BlockBreakEvent"
        function: "onBlockBreak"
        priority: "NORMAL"
    
    # Mappings for commands
    commands:
      test-command:
        aliases: ["test-command-alias"]             # Other names for this command
        description: "Eliminates the player"        # Comprehensive description
        permission: "handlerscriptloader.test"      # Permission required to execute
        usage: "/<command> [player]"                # Pops up, if false is returned
        function-exe: "onCommandTest"               # Executes the command
        function-tab: "onTabCompleteTest"           # Suggests arguments

# Toggles checks of updates released for LIX4J.
# Do not modify anything but 'enabled'.
updater:
  enabled: true