# handler-script-loader configuration
# 
# The LTSE language reference:
# https://github.com/inc0g-repoz/low-tier-script-engine
# 
# Make sure you are using valid event types. Use the link below for reference:
# https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/event/package-summary.html

# Function mapping
scripts:
  example:
    enabled: true
    file: "scripts/example.script"
    events:
      on-player-death:
        event-class: "org.bukkit.event.entity.PlayerDeathEvent"
        function: "onPlayerDeath"
        priority: "NORMAL"
      on-block-break:
        event-class: "org.bukkit.event.block.BlockBreakEvent"
        function: "onBlockBreak"
        priority: "NORMAL"