name: HandlerScriptLoader
version: 1.0
main: com.github.inc0grepoz.hsl.SpigotPlugin
author: LeadRounds
description: A script engine.

commands:
  handler-script-loader:
    aliases: [hsl]
    description: Reveals the plugin functionality
    permission: handlerscriptloader.reload
    usage: /<command> reload
