name: SpigotScriptLoader
version: 1.0
main: com.github.inc0grepoz.ssl.SpigotPlugin
author: LeadRounds
description: A script engine.

commands:
  spigot-script-loader:
    aliases: [ssl]
    description: Reveals the plugin functionality